language: node_js
node_js:
  - "8"

deploy:
    provider: script
    script: sh deploy.sh
    skip_cleanup: true
    on:
        tags: true
        
deploy:
  provider: gcs
  access_key_id: ${GCS_ID}
  secret_access_key: ${GCS_KEY}
  bucket: tutor-events
  skip_cleanup: true
  acl: public-read
  local-dir: dist
  on:
    tags: true